- name: Update Jenkins Role in Kubernetes
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if the file exists
      stat:
        path: jenkins-role.yaml
      register: file_stat

    - name: Add new rule to Jenkins Role
      blockinfile:
        path: jenkins-role.yaml
        block: |
          - apiGroups: ["*"]
            resources: ["pods", "services", "deployments"]
            verbs: ["get", "list", "create", "update", "delete"]
        insertafter: EOF
      when: file_stat.stat.exists

    - name: File does not contain header, adding it
      copy:
        content: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: jenkins-role
          rules:
            - apiGroups: ["*"]
              resources: ["pods", "services", "deployments"]
              verbs: ["get", "list", "create", "update", "delete"]
        dest: jenkins-role.yaml
      when: not file_stat.stat.exists




# The playbook first checks if the file "jenkins-role.yaml" exists (file_stat.stat.exists).
# If the file exists, it adds a new RBAC rule block to the file.
# If the file doesn't exist, it creates the file with a predefined RBAC rule content.
# This playbook is useful for ensuring that the "jenkins-role.yaml" file contains the required RBAC rules for interacting with Kubernetes resources.
